services:
  privategpt:
    build: 
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./models:/home/user/app/models
      - ./source_documents:/home/user/app/source_documents
    user: "${UID}:${GID}"

    # tty: true
    # stdin_open: true
    # command: /bin/bash
